a = int(input("enter the value of a:"))
b = int(input("enter the value of b:"))
c=a+b
print("sum=",c)
d=a-b
print("sub=",d)
e=a*b
print("mul=",e)
f=a/b
print("div=",f)
g=a%b
print("mod=",g)
h=a//b
print("double division=",h)
i=a**b
print("pow=",i)
